/**
 * Text scaffolding for executed notebooks (Phase B, ADR-0005 §1).
 *
 * The "prompt" name is from §5.1 of the project plan (N2 — LLM prompt
 * template for notebook authoring). In practice, Phase B is mostly
 * deterministic assembly: cells 0..4 + the footer are templated here, the
 * step-pair cells are translated from Phase A's tool calls in
 * `./tool-to-cell.ts`, and the synthesis-cell body reuses the chat-flow's
 * final answer text. No additional LLM call is required in Phase B for v1.
 *
 * The helper-functions cell (cell 3) is populated by reading the .py
 * source files in `./helpers/*.py` per ADR-0005 §3 (inline-embedded
 * source-of-truth).
 *
 * Attribution strings land INSIDE the signed datHere notebook (section E,
 * covered by contentHash), so they resolve through the instance-identity
 * config (ADR-0020, `src/lib/site-config.ts`). As of #258 there are no
 * identity defaults: on an instance that has declared no identity the
 * "via …" / "Generated by …" attribution is honestly OMITTED (authoring runs
 * on unsigned instances too; publishing such a notebook is separately
 * refused by the seal/commit gate). A configured instance emits exactly the
 * bytes it did before.
 */

import {
  getEvidenceSiteOrigin,
  getPublicationHost,
  getPlatformTitle,
} from '../site-config.ts';

/** Pinned scientific-stack versions; MUST match `scripts/build-sandbox-snapshot.ts`.
 *  All four pins target releases with prebuilt CPython 3.13 wheels so pip
 *  install on the Vercel Sandbox python3.13 runtime never needs a C
 *  compiler (which the runtime image does not ship). */
export const PINNED_LIBRARIES = {
  pandas: '2.2.3',
  requests: '2.32.3',
  numpy: '2.1.3',
  matplotlib: '3.9.2',
} as const;

/** Default Python runtime version baked into the Vercel Sandbox snapshot. */
export const PYTHON_RUNTIME_VERSION = '3.13';

/** Reverse-DNS extension keys per the Typed Standards Specification §8.7.4. */
export const NOTEBOOK_EXTENSION_KEY = 'org.civicaitools.notebook';
export const EXECUTION_EXTENSION_KEY = 'org.civicaitools.execution';
/** Phase 2a2: structured two-clause summary populated by the LLM in reproducible-notebook mode. */
export const SUMMARY_EXTENSION_KEY = 'org.civicaitools.summary';
/** Phase 2a2: marker for the rendering code cell whose outputs become section F. */
export const SYNTHESIS_CELL_ROLE = 'synthesis';

export function pinnedLibrariesPipList(): string {
  return Object.entries(PINNED_LIBRARIES)
    .map(([name, version]) => `${name}==${version}`)
    .join(' ');
}

export function buildCell0Source(args: {
  query: string;
  generatedAt: string;
  portals: readonly string[];
  /**
   * How many steps in this notebook re-run a data fetch (#341). Zero switches
   * the cover text to the honest version below: a notebook whose every fetch
   * failed contains no reproducible analysis, and the synthesis cell falls
   * back to displaying the original answer, so its figures would otherwise
   * read as a conclusion with nothing behind them.
   *
   * Optional so the parameter can be added without a silent behaviour change
   * at call sites that do not know the count; the production caller
   * (`synthesize.ts`) always passes it, and a test pins that it does.
   */
  reproducedFetchCount?: number;
}): string {
  const portalLine = args.portals.length === 0
    ? ''
    : `**Portal${args.portals.length > 1 ? 's' : ''}:** ${args.portals.join(', ')}  \n`;
  // #258: attribution only when this instance has declared an identity —
  // honest omission, never a substituted host.
  const host = getPublicationHost();
  const origin = getEvidenceSiteOrigin();
  const viaSuffix = host && origin ? ` via [${host}](${origin})` : '';
  // #324: the same conditional, applied to the title one line up. The heading
  // used to name the reference deployment on every instance, inside a file
  // readers download — while the attribution three lines below was already
  // honest about an undeclared identity. An instance that has declared none
  // gets the description without the name, never a borrowed one.
  const platformTitle = getPlatformTitle();
  const nothingReproduced = args.reproducedFetchCount === 0;
  return [
    platformTitle ? `# ${platformTitle} Data Analysis` : '# Data Analysis',
    '',
    `**Query:** ${args.query}  `,
    portalLine.trimEnd(),
    `**Generated:** ${args.generatedAt}${viaSuffix}`,
    '',
    '## How to use this notebook',
    '',
    ...(nothingReproduced
      ? [
        'No data was fetched when this notebook ran: every request to a live data',
        'source returned no data, so no step below reproduces one. The steps record',
        'what was attempted. Any figures in the "Synthesis" cell come from the',
        'original analysis text, not from data this notebook fetched — re-running',
        'the cells will not reproduce them.',
      ]
      : [
        'This notebook contains a complete, reproducible analysis of the query above.',
        'Every code cell that fetches data uses the helper functions defined below,',
        'so the same numbers can be reproduced against live data by re-running cells',
        'top-to-bottom. The final "Synthesis" cell explains what the data shows.',
      ]),
    '',
    '## Notebook structure',
    '',
    '- **Environment setup** — Python version check + pip install of pinned versions.',
    '- **Imports** — `requests`, `pandas`, `numpy`, `matplotlib`.',
    '- **Helper functions** — `fetch_socrata`, `fetch_data_commons`, `fetch_opencontext`',
    '  (only the helpers this analysis actually uses are included).',
    '- **Data analysis pipeline** — one step per discovery call.',
    '- **Synthesis** — narrative answer derived from the data above.',
    '- **Comparison: original vs. current** — appended at publish time; shows',
    '  whether the numbers have drifted since the notebook was first executed.',
    '- **Citations & reproducibility** — datasets, runtime, and re-run guidance.',
  ].filter(line => line !== '').join('\n');
}

export function buildCell1Source(): string {
  return [
    '# Environment setup',
    '#',
    '# Check the Python runtime and install pinned scientific-stack versions.',
    '# Re-execute this cell on a fresh kernel; subsequent runs are no-ops.',
    '',
    'import sys',
    `print(f"Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")`,
    '',
    '# !pip install --quiet ' + pinnedLibrariesPipList(),
  ].join('\n');
}

export function buildCell2Source(): string {
  return [
    '# Imports',
    'import os',
    'import json',
    'import requests',
    'import pandas as pd',
    'import numpy as np',
    'import matplotlib.pyplot as plt',
    '',
    'pd.set_option("display.max_columns", 80)',
    'pd.set_option("display.width", 200)',
  ].join('\n');
}

export const CELL_4_HEADER = '## Data Analysis Pipeline\n\nEach step below corresponds to one discovery call from the original analysis. The same helper functions and arguments are used so the analysis is fully reproducible.';

export function buildFooterCellSource(args: {
  citations: readonly { id: string; label: string; url: string }[];
  generatedAt: string;
  /** The operator-declared model identity — never a deployment name. */
  modelName: string;
  /**
   * How this instance reached that model, from `modelAccessPhrase()`
   * (src/lib/model-catalog.ts). Supplied by the caller rather than read here:
   * this module is imported by client components, and the dialect lives behind
   * the SDK-bearing endpoint layer.
   */
  modelAccess: string;
}): string {
  const lines = [
    '---',
    '',
    '## Citations',
    '',
  ];
  if (args.citations.length === 0) {
    lines.push('*(No external dataset citations were captured for this analysis.)*');
  } else {
    for (const c of args.citations) {
      lines.push(`- [${c.label || c.id}](${c.url})`);
    }
  }
  lines.push(
    '',
    '## Reproducibility',
    '',
    `- **Runtime:** Python ${PYTHON_RUNTIME_VERSION} with pinned libraries (\`${pinnedLibrariesPipList()}\`).`,
    // website#30 P3 (E6): "via OpenRouter" was the reference deployment's own
    // gateway, hardcoded into every instance's notebook. The identity is now
    // the operator-declared one and the endpoint is described by dialect —
    // never by resource host, which belongs to whoever deployed this and not
    // in a published record.
    `- **Author model:** ${args.modelName}, reached over ${args.modelAccess}.`,
    `- **Generated:** ${args.generatedAt}.`,
    '',
    'To re-execute: open in any Jupyter environment with the pinned versions installed and run all cells top-to-bottom. Compare original-vs-current values via the comparison cell appended at publish time.',
  );
  // #258: "Generated by …" only when this instance has declared an identity.
  const title = getPlatformTitle();
  const origin = getEvidenceSiteOrigin();
  if (title && origin) {
    lines.push('', `Generated by [${title}](${origin}).`);
  }
  return lines.join('\n');
}

/**
 * Phase 2a2: structured two-clause summary populated by the LLM. Both
 * clauses are short (recommended ≤ 140 chars). Section G renders these as
 * the citation-ready blurb; CITATION block can use them too.
 */
export interface StructuredSummary {
  analysisDescription: string;
  headlineFinding: string;
}

export interface ParsedSynthesisOutput {
  /** Structured summary parsed from a leading ```json``` block; null if missing or invalid. */
  summary: StructuredSummary | null;
  /** Python code parsed from a ```python``` block; null if missing. */
  synthesisCode: string | null;
}

/**
 * Phase 2a2 (item 3 + skill guidance C5): parse the LLM's reproducible-mode
 * answer into (a) the structured two-clause summary and (b) the synthesis
 * code cell body. The LLM is instructed via web.md to emit a leading
 * ```json``` block with `{ analysisDescription, headlineFinding }` and a
 * ```python``` block with the synthesis-cell body. Either may be absent on
 * imperfect LLM output; callers fall back gracefully.
 */
export function parseSynthesisOutput(rawAnswer: string): ParsedSynthesisOutput {
  if (!rawAnswer) return { summary: null, synthesisCode: null };
  let summary: StructuredSummary | null = null;
  const jsonMatch = rawAnswer.match(/```json\s*\r?\n([\s\S]*?)\r?\n```/i);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);
      if (
        parsed && typeof parsed === 'object' &&
        typeof (parsed as Record<string, unknown>).analysisDescription === 'string' &&
        typeof (parsed as Record<string, unknown>).headlineFinding === 'string'
      ) {
        summary = {
          analysisDescription: (parsed as Record<string, string>).analysisDescription.trim(),
          headlineFinding: (parsed as Record<string, string>).headlineFinding.trim(),
        };
      }
    } catch {
      // ignore — fall back to null summary
    }
  }
  let synthesisCode: string | null = null;
  const pyMatch = rawAnswer.match(/```python\s*\r?\n([\s\S]*?)\r?\n```/i);
  if (pyMatch) synthesisCode = pyMatch[1];
  return { summary, synthesisCode };
}

/** Indent every line of `body` by `prefix` for embedding into Python control
 *  flow (try/except, def, etc.). Preserves blank lines as blank-prefix lines
 *  per PEP 8. */
function indentPython(body: string, prefix: string): string {
  const lines = body.split('\n');
  return lines.map((line) => (line.length === 0 ? '' : prefix + line)).join('\n');
}

/**
 * Phase 2a2 (item 2): the rendering code cell body. When the LLM provides
 * a synthesis code block via the skill-guidance convention, that block is
 * wrapped in a try/except so an LLM-authoring mistake (NameError on a
 * wrong DataFrame name, KeyError on an unexpected column, SyntaxError-free
 * but runtime-raising expression) does NOT take down the whole notebook
 * execution. On exception, the cell prints a short diagnostic and falls
 * back to rendering the raw chat-flow answer as markdown so the user still
 * gets a useful section F. The cell metadata.role === "synthesis" marker
 * stays attached either way so the chat-output extractor finds it.
 *
 * When the LLM omits the ```python``` block entirely, we skip the try/except
 * and just render the raw chat-flow answer as markdown via display(Markdown).
 *
 * ADR-0005 §1 Phase C envisions a retry-once loop with the failure in the
 * LLM's context; the try/except wrapper here is the lighter-weight defense
 * appropriate to the synthesis cell specifically (the rest of the notebook
 * still benefits from the full retry loop once that lands).
 */
export function buildSynthesisCellSource(args: {
  synthesisCode: string | null;
  rawAnswer: string;
}): string {
  const fallbackBody = (args.rawAnswer ?? '').trim() || '_No synthesis was produced for this analysis._';
  const fallbackPyLiteral = JSON.stringify(fallbackBody);
  if (args.synthesisCode && args.synthesisCode.trim().length > 0) {
    const llmBody = args.synthesisCode.trimEnd();
    return [
      '# Synthesis — rendered answer for the query above. This cell\'s outputs',
      '# become section F of the A-G envelope (Typed Standards Specification §8.7.4 / ADR-0005).',
      'from IPython.display import display, Markdown',
      '',
      'try:',
      indentPython(llmBody, '    '),
      'except Exception as _civic_synth_err:',
      '    # LLM-emitted synthesis raised — fall back to the raw chat-flow answer',
      '    # so the synthesis cell still produces a useful section F output.',
      '    print(',
      '        f"\\u26A0 Synthesis code raised "',
      '        f"{type(_civic_synth_err).__name__}: {_civic_synth_err}. "',
      '        f"Falling back to the chat-flow answer.",',
      '    )',
      `    display(Markdown(${fallbackPyLiteral}))`,
    ].join('\n');
  }
  return [
    '# Synthesis — rendered answer for the query above. This cell\'s outputs',
    '# become section F of the A-G envelope (Typed Standards Specification §8.7.4 / ADR-0005).',
    '# Fallback path: the LLM did not emit a ```python``` block, so the chat-flow',
    '# answer is rendered verbatim as markdown.',
    'from IPython.display import display, Markdown',
    '',
    `display(Markdown(${fallbackPyLiteral}))`,
  ].join('\n');
}
