/**
 * Guard: every design token referenced in the app resolves to a definition.
 *
 * A `var(--typo)` is silent. CSS drops the declaration and the element inherits
 * or falls back to its initial value, so a mistyped token renders as "slightly
 * wrong color" on one surface and nothing anywhere reports it — no build error,
 * no console warning, no failing test. `--nyc-gray-50` lived on production that
 * way: referenced once, defined never, invisible because the call site happened
 * to carry a fallback.
 *
 * That risk is at its highest during a token rename (#220 P3 moved 306 call
 * sites off the `--nyc-*` names), which is why this exists. It is not a
 * rename-only check though — it earns its keep on any day someone adds a
 * reference to a token that does not exist.
 *
 * What it does NOT catch: a reference that resolves to the WRONG defined token.
 * `--neutral-70` mistyped as `--neutral-80` passes here and renders wrong. That
 * failure mode is diff-shaped, not state-shaped — it is only visible against a
 * before/after — so it is checked at review time against the diff rather than
 * here.
 *
 * The two allowlists below are deliberately written as explicit names and paths
 * rather than patterns. A pattern silently absorbs future additions; a named
 * entry means widening the carve-out is a reviewed act with a reason attached.
 *
 * ---
 *
 * SECOND GUARD, added by #405 (Wave N11, ruling D2): no colour LITERAL in a
 * `.ts` colour table. The first guard reads references and asks whether each
 * resolves; it cannot see the opposite failure, a colour that never asks for a
 * token at all. `src/components/tool-badges.ts` painted four operation types
 * with quoted hex for two waves, and `src/styles/page-styles.ts` carried
 * `rgba(112, 186, 255, …)` — which IS `--info`'s channel triplet, copied — and
 * neither was visible to the one test whose job is refusing colours that
 * resolve to nothing.
 *
 * ITS UNIVERSE IS DERIVED (ruling D10): every `.ts` file under `src/` that is
 * not a test, found by walking the tree, never a list of the files that
 * offend today. A colour table added tomorrow is in scope the moment it is
 * written.
 *
 * ITS BLIND SPOT, stated rather than left to be discovered: it does not read
 * `.tsx`. Measured at the time of writing, 30 non-test `.tsx` files carry 135
 * colour literals inline in JSX `style` props. That is a real backlog of the
 * same defect and this guard does not cover it — but it is a backlog, not a
 * carve-out, and no allowlist here hides it. The boundary is `.ts` rather than
 * a directory or a file list because a colour table is extracted into a `.ts`
 * sibling precisely so a test can read it without rendering
 * (`tool-badges.ts`'s own docstring says so): the `.ts` colour surface is the
 * one that is meant to be machine-checkable, and it is now checked whole.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(import.meta.url);
const APP_ROOT = path.dirname(HERE);
const SRC_ROOT = path.dirname(APP_ROOT);
const GLOBALS_CSS = path.join(APP_ROOT, 'globals.css');

/**
 * Tokens that are legitimately defined somewhere other than globals.css.
 * One line of justification each — if you add one, say who defines it.
 */
const DEFINED_ELSEWHERE: Record<string, string> = {
  '--header-height':
    'set at runtime on <html> by Header.tsx, from the measured header element',
  '--font-space-grotesk':
    "generated by next/font/local in layout.tsx (localFont({ variable: '--font-space-grotesk' }))",
  '--font-noto-sans':
    "generated by next/font/local in layout.tsx (localFont({ variable: '--font-noto-sans' }))",
  '--font-mono':
    "Tailwind's own default theme, pulled in by @import 'tailwindcss' in globals.css",
};

/**
 * Files that carry a self-contained token layer of their own and so are not
 * governed by globals.css. One line of justification each.
 */
const SELF_CONTAINED_FILES: Record<string, string> = {
  'app/(marketing)/talks/_decks/ctfg-vibe-code-2026-07.html':
    'a standalone deck served verbatim by talks/[deck]/route.ts; it declares its own :root palette inline and shares nothing with the app stylesheet',
};

const SCANNED_EXTENSIONS = /\.(css|ts|tsx|js|jsx|mjs|html)$/;

/** `var(--token)` or `var(--token, fallback)`. The trailing `)` or `,` is what
 *  separates a real reference from prose ("every `var(--font-*` name") and from
 *  a template-string prefix (`var(--c-` + key + `)`). */
const VAR_REFERENCE = /var\(\s*(--[A-Za-z0-9_-]+)\s*[,)]/g;

function sourceFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return sourceFiles(full);
    return SCANNED_EXTENSIONS.test(entry.name) ? [full] : [];
  });
}

/** Every custom property declared in globals.css, comments removed first so a
 *  commented-out declaration does not count as a definition. */
function definedTokens(): Set<string> {
  const css = fs.readFileSync(GLOBALS_CSS, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
  return new Set([...css.matchAll(/(--[A-Za-z0-9_-]+)\s*:/g)].map((m) => m[1]));
}

test('every referenced design token is defined', () => {
  const defined = definedTokens();
  const allowed = new Set(Object.keys(DEFINED_ELSEWHERE));
  const skipped = new Set(Object.keys(SELF_CONTAINED_FILES));

  const dangling: string[] = [];

  for (const file of sourceFiles(SRC_ROOT)) {
    if (file === HERE) continue;
    const rel = path.relative(SRC_ROOT, file);
    if (skipped.has(rel)) continue;

    const contents = fs.readFileSync(file, 'utf8');
    for (const match of contents.matchAll(VAR_REFERENCE)) {
      const token = match[1];
      if (defined.has(token) || allowed.has(token)) continue;
      const line = contents.slice(0, match.index).split('\n').length;
      dangling.push(`${rel}:${line}  ${token}`);
    }
  }

  assert.deepEqual(
    [...new Set(dangling)].sort(),
    [],
    'These var(--token) references resolve to nothing. CSS drops the ' +
      'declaration silently, so the element renders with an inherited or ' +
      'initial value instead of the intended one. Either define the token in ' +
      'src/app/globals.css, or — if it is genuinely a one-off with no place in ' +
      'the palette — use the literal value directly. If it is defined outside ' +
      'globals.css, add it to DEFINED_ELSEWHERE in this file with a reason.',
  );
});

/** A quoted CSS colour: `'#RGB'` through `'#RRGGBBAA'`, or an `rgb()`/`rgba()`
 *  whose first channel is a NUMBER. `rgba(var(--accent-rgb), 0.1)` is the
 *  sanctioned tint form and is deliberately not matched — it names a token. */
const COLOR_LITERAL = /['"`]#[0-9A-Fa-f]{3,8}['"`]|rgba?\(\s*[0-9][^)]*\)/g;

/** Comments blanked, so a `#258` inside a docstring is not a colour and a
 *  commented-out literal is not a live one. Newlines are preserved rather than
 *  removed so the reported line number is the file's own. */
function withoutComments(source: string): string {
  const blank = (match: string) => match.replace(/[^\n]/g, ' ');
  return source.replace(/\/\*[\s\S]*?\*\//g, blank).replace(/^\s*\/\/.*$/gm, blank);
}

test('no colour literal in a .ts colour table — colours are named', () => {
  const offenders: string[] = [];

  for (const file of sourceFiles(SRC_ROOT)) {
    if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
    const rel = path.relative(SRC_ROOT, file);
    const contents = withoutComments(fs.readFileSync(file, 'utf8'));
    for (const match of contents.matchAll(COLOR_LITERAL)) {
      const line = contents.slice(0, match.index).split('\n').length;
      offenders.push(`${rel}:${line}  ${match[0]}`);
    }
  }

  assert.deepEqual(
    offenders.sort(),
    [],
    'These are colours spelled out rather than named. A literal opts the element out of the ' +
      "palette: invisible on this instance, wrong on every other one, and it stops tracking the " +
      'token it was copied from the moment that token moves. Name a token from ' +
      'src/app/globals.css — `var(--token)` for a solid, `rgba(var(--token-rgb), α)` for a tint — ' +
      'and add the token there if the role has none.',
  );
});

test('every allowlist entry is still load-bearing', () => {
  // An allowlist that outlives its reason quietly widens the check. If an entry
  // no longer matches anything, the carve-out should go, not linger.
  const defined = definedTokens();

  const redundant = Object.keys(DEFINED_ELSEWHERE).filter((t) => defined.has(t));
  assert.deepEqual(
    redundant,
    [],
    'These tokens are now defined in globals.css, so their DEFINED_ELSEWHERE ' +
      'entries are dead. Remove them.',
  );

  const missingFiles = Object.keys(SELF_CONTAINED_FILES).filter(
    (rel) => !fs.existsSync(path.join(SRC_ROOT, rel)),
  );
  assert.deepEqual(
    missingFiles,
    [],
    'These SELF_CONTAINED_FILES entries point at files that no longer exist. ' +
      'Remove them so the carve-out cannot silently cover something else later.',
  );
});
