'use client';

import { useState } from 'react';

const GITHUB_BASE = 'https://github.com/npstorey/civic-ai-tools-website/blob/main/src/lib/streaming.ts';

const SOURCE_FUNCTIONS = [
  {
    name: 'formatToolProgress',
    lines: '#L43-L71',
    description: 'Generates action descriptions like "Searching for restaurant inspection datasets"',
  },
  {
    name: 'formatToolResult',
    lines: '#L319-L343',
    description: 'Summarizes results like "Found 5 datasets" or "Retrieved 100 rows"',
  },
  {
    name: 'generateToolReason',
    lines: '#L346-L370',
    description: 'Explains purpose like "Finding available datasets before querying"',
  },
];

export default function NarrationExplainer() {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div style={{ marginTop: '4px' }}>
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        style={{
          background: 'none',
          border: 'none',
          color: 'var(--accent)',
          fontSize: '12px',
          fontWeight: 500,
          cursor: 'pointer',
          padding: 0,
          textDecoration: 'underline',
        }}
      >
        How is this narration generated?
      </button>

      {isExpanded && (
        <div
          style={{
            backgroundColor: 'var(--card-background)',
            border: '1px solid var(--border-color)',
            borderRadius: '4px',
            padding: '12px 16px',
            marginTop: '8px',
            fontSize: '13px',
            lineHeight: '1.5',
            color: 'var(--text-secondary)',
          }}
        >
          <p style={{ margin: '0 0 10px 0' }}>
            The step descriptions above are generated by interface code, not by the AI.
            Three functions transform raw API calls into readable narration:
          </p>

          <ul style={{ margin: '0 0 10px 0', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {SOURCE_FUNCTIONS.map((fn) => (
              <li key={fn.name}>
                <a
                  href={`${GITHUB_BASE}${fn.lines}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ fontFamily: 'monospace', color: 'var(--accent)', textDecoration: 'underline' }}
                >
                  {fn.name}
                </a>
                {' '}&mdash; {fn.description}
              </li>
            ))}
          </ul>

          <p style={{ margin: '0 0 8px 0', fontSize: '12px', color: 'var(--text-muted)', fontStyle: 'italic' }}>
            This is similar to how a chart is an interpretation of raw numbers &mdash; the data is real,
            but the presentation is a design choice.
          </p>

          <a
            href="/learn#narration"
            style={{ fontSize: '12px', color: 'var(--accent)', textDecoration: 'underline' }}
          >
            Learn more about how the demo works &rarr;
          </a>
        </div>
      )}
    </div>
  );
}
